conversation/urls.py
from django.urls import path

from . import views

app_name = 'conversation'

urlpatterns = [
  path('new/<int:item_pk>/', views.new_conversation, name='new'),
  path('', views.inbox, name='inbox'),
  path('<int:pk>/', views.detail, name='detail'),
]

core/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views


from . import views
from .forms import LoginForm
app_name = 'core'

urlpatterns = [
  path('', views.index, name='index'),
  path('contact/', views.contact, name='contact'),
  path('about/', views.about, name='about'),  
  path('policy/', views.policy, name='policy'),
  path('termsofuse/', views.termsOfUse, name='termsofuse'),
  path('signup/', views.signup, name='signup'),
  path('logout/', views.logout, name='logout'),
  path('login/', auth_views.LoginView.as_view(template_name='core/login.html', authentication_form=LoginForm), name='login'), 
]

dashboard/urls.py
from django.urls import path

from . import views

app_name = 'dashboard'

urlpatterns = [
    path('', views.index, name='index'),
]

item/urls.py
from django.urls import path
from . import views

app_name = 'item'

urlpatterns = [
  path('', views.items, name='items'),
  path('new/', views.new, name='new'),
  path('<int:item_id>/', views.detail, name='detail'),
  path('<int:item_id>/delete/', views.delete, name='delete'),
  path('<int:item_id>/edit/', views.edit, name='edit'),
  
]

puddle/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('core.urls')),
    path('item/', include('item.urls')),
    path('admin/', admin.site.urls),
    path('inbox/', include('conversation.urls')),
    path('dashboard/', include('dashboard.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/models.py
from django.db import models

# Create your models here.

core/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User

class LoginForm(AuthenticationForm):
  username = forms.CharField(widget=forms.TextInput(attrs={
    'placeholder': 'Your username',
    'class': 'w-full py-4 px-6 rounded-xl'
    }), max_length=30, required=True, help_text='Required. 30 characters or fewer. Letters, digits and @/./+/-/_ only.')
  password = forms.CharField(widget=forms.PasswordInput(attrs={
    'placeholder': 'Your Password',
    'class': 'w-full py-4 px-6 rounded-xl'
    }), required=True)
  

class SignupForm(UserCreationForm):
  class Meta:
    model = User
    fields = ('username', 'email', 'password1', 'password2')
    
  username = forms.CharField(widget=forms.TextInput(attrs={
    'placeholder': 'Your username',
    'class': 'w-full py-4 px-6 rounded-xl'
    }), max_length=30, required=True, help_text='Required. 30 characters or fewer. Letters, digits and @/./+/-/_ only.')
  
  email = forms.CharField(widget=forms.EmailInput(attrs={
    'placeholder': 'Your email',
    'class': 'w-full py-4 px-6 rounded-xl'
    }), required=True)
  password1 = forms.CharField(widget=forms.PasswordInput(attrs={
    'placeholder': 'Your Password',
    'class': 'w-full py-4 px-6 rounded-xl'
    }), required=True)
  
  password2 = forms.CharField(widget=forms.PasswordInput(attrs={
    'placeholder': 'Repeat Password',
    'class': 'w-full py-4 px-6 rounded-xl'
    }), required=True)
  

core/views.py
from django.shortcuts import render, redirect
from item.models import Category, Item
from django.contrib.auth import logout as auth_logout

from .forms import SignupForm

# Create your views here.
def index(request):
    items = Item.objects.filter(is_sold=False)[0:15]
    categories = Category.objects.all()
    return render(request, 'core/index.html', context={'items': items, 'categories': categories})

def contact(request):
    return render(request, 'core/contact.html')

def about(request):
    return render(request, 'core/about.html')

def policy(request):
    return render(request, 'core/policy.html')

def termsOfUse(request):
    return render(request, 'core/termsofuse.html')

def signup(request):
    if request.method == 'POST':
        form = SignupForm(request.POST)
        if form.is_valid():
            form.save()
            
            return redirect('/login/')
    else:
        form = SignupForm()
        
    return render(request, 'core/signup.html', {'form': form})

def logout(request):
    auth_logout(request)
    return redirect('/login/')

core/templates/core/about.html
{% extends 'core/base.html' %} 

{% block title %}About{% endblock %} 

{% block content %}
<h1><b>About Us</b></h1>
<p>Interdum et malesuada fames ac ante ipsum primis in faucibus. Maecenas vulputate elit ut sem bibendum, nec rutrum ex iaculis. Donec erat enim, bibendum nec mattis eget, interdum euismod nisi. Mauris mattis, tortor eu tempor commodo, nunc tellus dignissim justo, vehicula faucibus ipsum sem sit amet ligula. Cras sed accumsan erat. Integer molestie ipsum quis justo gravida euismod. In a auctor ligula. Ut ac enim vel dolor malesuada dapibus.
Aenean sit amet quam a ex mattis euismod nec at lectus. Nullam nisi mauris, eleifend eu ligula eget, vehicula tincidunt nulla. Duis congue congue consequat. Duis pellentesque laoreet ex, a fermentum purus laoreet ac. Pellentesque sed lacus non arcu imperdiet tincidunt a vel eros. Pellentesque venenatis leo in mattis varius. Ut libero massa, maximus ut odio eu, egestas vestibulum tortor. Donec hendrerit congue erat eget tempor. Praesent quis aliquet arcu, nec consectetur nisi. Maecenas varius ligula vitae cursus sodales. Aenean tristique imperdiet eleifend. Fusce at ex nec mi tristique blandit eget vitae metus.</p>
{% endblock %}

core/templates/core/base.html
<!DOCTYPE html>

<html>
  <head>
    <meta charset="utf-8" />
    <meta name="description" content="width=device-width, initial-sclae=1.0" />

    <script src="https://cdn.tailwindcss.com"></script>

    <title>{% block title %} {% endblock %} | Puddle</title>
  </head>

  <body>
    <nav class="py-6 px-6 flex justify-between items-center border-b border-gray-200">
      <a href="/" class="text-xl font-semibold">Puddle</a>

      <div class="space-x-6">
        <a href="{% url 'item:new' %}" class="text-lg font-semibold hover:text-gray-500">New item</a>
        <a href="{% url 'item:items' %}" class="text-lg font-semibold hover:text-gray-500">Browse</a>
        {% if request.user.is_authenticated %}
          <a href="{% url 'conversation:inbox' %}" class="px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700">Inbox</a>
          <a href="{% url 'dashboard:index' %}" class="px-6 py-3 text-lg font-semibold bg-gray-500 text-white rounded-xl hover:bg-gray-700">Dashboard</a>
          <a href="{% url 'core:logout' %}" class="text-lg font-semibold hover:text-gray-500">Log out</a>
        
        {% else %}
          <a href="{% url 'core:signup' %}" class="px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700">Sign Up</a>
          <a href="{% url 'core:login' %}" class="px-6 py-3 text-lg font-semibold bg-gray-500 text-white rounded-xl hover:bg-gray-700">Log in</a>
        {% endif %}

      </div>
    </nav>

    <div class="px-6 py-6">
      {% block content %} {% endblock %}
    </div>
    
    <footer class="py-6 px-6 flex justify-between bg-gray-800">
      <div class="w-2/3 pr-10">
        <h3 class="mb-5 font-semibold text-gray-400">About</h3>
        <p class="text-lg text-gray-500">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque hendrerit semper orci, semper sodales sapien gravida sit amet. Quisque congue luctus velit, a facilisis nibh gravida eget. Fusce aliquam enim lacus, a viverra justo faucibus vel. Nam quis erat lacinia, dignissim risus vel, interdum ante.</p>
      </div>

      <div class="w-1/3">
        <h3 class="mb-5 font-semibold text-gray-400">Menu</h3>

        <ul class="space-y-2">
          <li><a href="{% url 'core:about' %}" class="text-lg text-teal-500 hover:text-teal-700">About</a></li>
          <li><a href="{% url 'core:contact' %}" class="text-lg text-teal-500 hover:text-teal-700">Contact</a></li>
          <li><a href="{% url 'core:policy' %}" class="text-lg text-teal-500 hover:text-teal-700">Privacy Policy</a></li>
          <li><a href="{% url 'core:termsofuse' %}" class="text-lg text-teal-500 hover:text-teal-700">Terms of Use</a></li>

        </ul>
      </div>
    </footer>
  </body>
</html>

core/templates/core/contact.html
{% extends 'core/base.html' %} 

{% block title %}Contact{% endblock %} 


{% block content %}
<h1><b>Contact</b></h1>
<p>Interdum et malesuada fames ac ante ipsum primis in faucibus. Maecenas vulputate elit ut sem bibendum, nec rutrum ex iaculis. Donec erat enim, bibendum nec mattis eget, interdum euismod nisi. Mauris mattis, tortor eu tempor commodo, nunc tellus dignissim justo, vehicula faucibus ipsum sem sit amet ligula. Cras sed accumsan erat. Integer molestie ipsum quis justo gravida euismod. In a auctor ligula. Ut ac enim vel dolor malesuada dapibus.
Aenean sit amet quam a ex mattis euismod nec at lectus. Nullam nisi mauris, eleifend eu ligula eget, vehicula tincidunt nulla. Duis congue congue consequat. Duis pellentesque laoreet ex, a fermentum purus laoreet ac. Pellentesque sed lacus non arcu imperdiet tincidunt a vel eros. Pellentesque venenatis leo in mattis varius. Ut libero massa, maximus ut odio eu, egestas vestibulum tortor. Donec hendrerit congue erat eget tempor. Praesent quis aliquet arcu, nec consectetur nisi. Maecenas varius ligula vitae cursus sodales. Aenean tristique imperdiet eleifend. Fusce at ex nec mi tristique blandit eget vitae metus.</p>
{% endblock %}

core/templates/core/index.html
{% extends 'core/base.html' %} 

{% block title %}Welcome{% endblock %} 

{% block content %}
  <div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
    <h2 class="mb-12 text-2xl text-center">Newest Items</h2>

    <div class="grid grid-cols-3 gap-3">
      {% for item in items %}
        <div>
          <a href="{% url 'item:detail' item.id %}">
            <div>
              <img src="{{ item.image.url }}" class="rounded-t-xl">
            </div>

            <div class="p-6 bg-white rounded-b-xl">
              <h2 class="text-xl">{{ item.name }}</h2>
              <p class="text-gray-500">Price: {{ item.price }}</p>
            </div>
          </a>
        </div>
      {% endfor %}
    </div>
  </div>

  <div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
    <h2 class="mb-12 text-2xl text-center">Categories</h2>

    <div class="grid grid-cols-3 gap-3">
      {% for category in categories %}
        <div>
          <a href="{% url 'item:items' %}?category={{ category.id }}">
            <div class="p-6 bg-white rounded-b-xl">
              <h2 class="text-xl">{{ category.name }}</h2>
              <p class="text-gray-500">{{ category.items.count }} items</p>
            </div>
          </a>
        </div>
      {% endfor %}
    </div>
  </div>

{% endblock %}

core/templates/core/login.html
{% extends 'core/base.html' %} 

{% block title %}Login{% endblock %}



{% block content %} 
<div class="w-1/2 my-6 mx-auto p-6 bg-gray-100 rounded-xl">
  <h1 class="mb-6 text-3xl">Log in</h1>

  <form method="post" action=".">
    {% csrf_token %}

    <div class="mb-3">
      <label class="inline-block mb-2">Username</label><br>
      {{ form.username }}
    </div>

    <div class="mb-3">
      <label class="inline-block mb-2">Password</label><br>
      {{ form.password }}
    </div>
  
    {% if form.errors or form.non_field_errors %}
      <div class="mb-3 p-6 bg-red-100 rounded-xl">

        {% for field in form %}
          {{ field.errors }}
        {% endfor %}
        {{ form.non_field_errors }}

      </div>

    {% endif %}

    <button class="py-4 px-8 text-lg bg-teal-500 hover:bg-teal-700 rounded-xl text-white">Log in</button>


  </form>
</div>
{% endblock %}

core/templates/core/policy.html
{% extends 'core/base.html' %} 

{% block title %}Privacy Policy{% endblock %} 


{% block content %}
<h1><b>Privacy Policy</b></h1>
<p>Interdum et malesuada fames ac ante ipsum primis in faucibus. Maecenas vulputate elit ut sem bibendum, nec rutrum ex iaculis. Donec erat enim, bibendum nec mattis eget, interdum euismod nisi. Mauris mattis, tortor eu tempor commodo, nunc tellus dignissim justo, vehicula faucibus ipsum sem sit amet ligula. Cras sed accumsan erat. Integer molestie ipsum quis justo gravida euismod. In a auctor ligula. Ut ac enim vel dolor malesuada dapibus.
Aenean sit amet quam a ex mattis euismod nec at lectus. Nullam nisi mauris, eleifend eu ligula eget, vehicula tincidunt nulla. Duis congue congue consequat. Duis pellentesque laoreet ex, a fermentum purus laoreet ac. Pellentesque sed lacus non arcu imperdiet tincidunt a vel eros. Pellentesque venenatis leo in mattis varius. Ut libero massa, maximus ut odio eu, egestas vestibulum tortor. Donec hendrerit congue erat eget tempor. Praesent quis aliquet arcu, nec consectetur nisi. Maecenas varius ligula vitae cursus sodales. Aenean tristique imperdiet eleifend. Fusce at ex nec mi tristique blandit eget vitae metus.</p>
{% endblock %}

core/templates/core/signup.html
{% extends 'core/base.html' %} 

{% block title %}Sign up{% endblock %}



{% block content %} 
<div class="w-1/2 my-6 mx-auto p-6 bg-gray-100 rounded-xl">
  <h1 class="mb-6 text-3xl">Sign Up</h1>

  <form method="post" action=".">
    {% csrf_token %}

    <div class="mb-3">
      <label class="inline-block mb-2">Username</label><br>
      {{ form.username }}
    </div>


    <div class="mb-3">
      <label class="inline-block mb-2">Email</label><br>
      {{ form.email }}
    </div>

    <div class="mb-3">
      <label class="inline-block mb-2">Password</label><br>
      {{ form.password1 }}
    </div>
    <div class="mb-3">
      <label class="inline-block mb-2">Repeat Password</label><br>
      {{ form.password2 }}
    </div>

    {% if form.errors or form.non_field_errors %}
      <div class="mb-3 p-6 bg-red-100 rounded-xl">

        {% for field in form %}
          {{ field.errors }}
        {% endfor %}
        {{ form.non_field_errors }}

      </div>

    {% endif %}

    <button class="py-4 px-8 text-lg bg-teal-500 hover:bg-teal-700 rounded-xl text-white">Submit</button>



  </form>
</div>
{% endblock %}

core/templates/core/termsofuse.html
{% extends 'core/base.html' %} 

{% block title %}Terms of Use{% endblock %} 


{% block content %}
<h1><b>Terms of Use</b></h1>
<p>Interdum et malesuada fames ac ante ipsum primis in faucibus. Maecenas vulputate elit ut sem bibendum, nec rutrum ex iaculis. Donec erat enim, bibendum nec mattis eget, interdum euismod nisi. Mauris mattis, tortor eu tempor commodo, nunc tellus dignissim justo, vehicula faucibus ipsum sem sit amet ligula. Cras sed accumsan erat. Integer molestie ipsum quis justo gravida euismod. In a auctor ligula. Ut ac enim vel dolor malesuada dapibus.
Aenean sit amet quam a ex mattis euismod nec at lectus. Nullam nisi mauris, eleifend eu ligula eget, vehicula tincidunt nulla. Duis congue congue consequat. Duis pellentesque laoreet ex, a fermentum purus laoreet ac. Pellentesque sed lacus non arcu imperdiet tincidunt a vel eros. Pellentesque venenatis leo in mattis varius. Ut libero massa, maximus ut odio eu, egestas vestibulum tortor. Donec hendrerit congue erat eget tempor. Praesent quis aliquet arcu, nec consectetur nisi. Maecenas varius ligula vitae cursus sodales. Aenean tristique imperdiet eleifend. Fusce at ex nec mi tristique blandit eget vitae metus.</p>
{% endblock %}